### ISSUE TITLE
The link to Roy Dyckhoff's LJT in the readme is broken

### ISSUE THREAD

**Issue by expipiplus1** [ayberkt/sequents#23]

**Comment by ayberkt** [comment]
@expipiplus1 thanks for pointing this out. The link is not "broken", to be technically precise, but the page it points to raises some kind of security warning. This will be fixed by #23 which changes the README to use the JSTOR link of the mentioned publication instead.

**Comment by expipiplus1** [comment]
@ayberkt If I click through the security warning it 404s. Glad to hear #23 fixes this :)

**Comment by ayberkt** [comment]
> If I click through the security warning it 404s

Ah, I see. I've never noticed that and thought you meant the security warning.
